### ISSUE TITLE
[Feature-Request]: ResetStates and WaitForState to work in unity editor

### ISSUE THREAD

**Issue by maclo4** [playroomkit/unity#108]
### What do you want to see?

Pretty much just what the title says. The code for those just doesn't get hit bc it's not being run im the browser. Some sort of locally stored response would be great.

**Comment by momintlh** [comment]
Hi, @maclo4 this will be fixed in the next release.

**Comment by SaadBazaz** [comment]
Added in v1.0.3beta: https://github.com/playroomkit/unity/releases/tag/v1.0.3beta
