### ISSUE TITLE
Refactor PlayroomKit 

### ISSUE THREAD

**Issue by momintlh** [playroomkit/unity#40]
This isn't a feature/bug issue but rather an issue for refactoring/cleaning the SDK. As we are using callbacks in many parts of the C# wrapper, it is getting quite messy, we have the following pattern in multiple parts:
``` C#
private static Action SomeCallback = null;

[DllImport("__Internal")]
private static extern void InternalJSLIBFunction(Action callback)

// Callback Invoker
[MonoPInvokeCallback(typeof(Action))]
private static void CallBackInvoker()
{
    SomeCallback?.Invoke();
}

// Exposed Function
public static void ExposedFunction(Action callback) 
{
SomeCallback = callback;
InternalJSLIBFunction(CallBackInvoker);
}
```  

And to use the function we usually do something like this:
``` C#
PlayroomKit.ExposedFunction(() = > {
   // Do Something when callback is invoked
})
``` 
or
```C#
PlayroomKit.ExposedFunction(callback);
void callback() 
{
// Do Something when callback is invoked
}
```

What we can do is to make a custom class for handling callbacks this will simplify the current codebase and make it easier for future updates/fixes.

**Comment by SaadBazaz** [comment]
Yeah a class for Callbacks (kind of like a CallbackFactory or something) might be cool.

Also, can use Macros for repetitive code, like the `if playroom is not initialized` guard.

**Comment by momintlh** [comment]
### Side by side working of JSLIB & C# handling callbacks:

![Untitled-2023-12-04-2253](https://github.com/asadm/playroom-unity/assets/77355191/4bc115d2-2aa4-48f3-b28c-dca20d7adbce)

**Comment by SaadBazaz** [comment]
We need better error handling to distinguish between JS errors and Unity errors. Inspired by #38

**Comment by SaadBazaz** [comment]
Thoughts on filestructure:
```
utils
|_ CallbackFactory.cs
|_ Errors.cs
modules
|_ PlayroomKit
  |_ PlayroomKit.h // <-- declaration file
  |_ PlayroomKit.cs // <-- definition file
  |_ PlayroomKit.mock.cs // <-- mockmode file (only overrides the functions which are defined here, other should be same as definition file
  |_ Player
    |_ ... // <-- similar 3 files here
    |_ Profile
      |_ Profile.cs // <-- similar 3 files here
      |_ Color.cs // <-- similar 3 files here
```

**Comment by SaadBazaz** [comment]
My thoughts on how we can implement Mock Mode in a more structured, cleaner manner. Code is in JS but you may get the gist:

![image](https://github.com/asadm/playroom-unity/assets/51885228/d8b694bd-7367-4ce9-81f9-042c18cb2175)

**Comment by momintlh** [comment]
> My thoughts on how we can implement Mock Mode in a more structured, cleaner manner. Code is in JS but you may get the gist:


Our base class is a static class with static members, inheritance and overriding isn't going to work with that.

**Comment by SaadBazaz** [comment]
> Our base class is a static class with static members, inheritance and overriding isn't going to work with that.

Maybe create a common interface on top?

**Comment by SaadBazaz** [comment]
We need to decouple the NetworkManager from the PlayroomKit API. That will enable us to create an implementation for WebGL vs mobile vs desktop

**Comment by SaadBazaz** [comment]
PlayroomKit interface is yet to be made @momintlh

**Comment by momintlh** [comment]
> PlayroomKit interface is yet to be made @momintlh 
> 

Base Interface / abstract class? Yes

**Comment by SaadBazaz** [comment]
We will now track this in the project, in the form of separate tasks.
